default_config = {
    'random_seed': 42,
    'buffer_size': 10_000,
    'batch_size': 128,
    'discount': 0.99,
    'tau': 1e-3,
    'actor_lr': 1e-4,
    'critic_lr': 1e-3,
    'weight_decay': 1e-5,
    'episodes': 1000,
    'max_timesteps': 500,
    'encoder_layers': [8],
    'actor_layers': [8, 
        100, 'ReLU',
        # 100, 'ReLU', 'BN',
        # 8, 'ReLU', 'BN',
        # 8, 'ReLU', 'BN',
        # 8, 'ReLU', 'BN',
        # 8, 'ReLU', 'BN',
        # 8, 'ReLU', 'BN',
        # 8, 'ReLU', 'BN',
        # 8, 'ReLU', 'BN',
        # 8, 'ReLU', 'BN',
        # 8, 'ReLU', 'BN',
        # 8, 'ReLU', 'BN',
        # 8, 'ReLU', 'BN',
        100, 'ReLU',  2, 'tanh'],
    'critic_layers': [
        8 + 2, 
        100, 'ReLU', 'BN', 
        # 100, 'ReLU', 'BN',
        # 10, 'ReLU', 'BN',
        # 10, 'ReLU', 'BN', 
        # 10, 'ReLU', 'BN', 
        # 10, 'ReLU', 'BN', 
        # 10, 'ReLU', 'BN', 
        # 10, 'ReLU', 'BN', 
        # 10, 'ReLU', 'BN', 
        100, 'ReLU', 'BN', 1],
    'noise_var': 1,
    'min_noise_var': 0.1,
    'noise_var_decay_rate': 1e-4,
    'render_every': 1,
    'n_random_episodes': 0
}